module.exports = {
    purge: [
        "./src/**/*.php",
        "./src/**/*.html",
        "./src/**/*.js",
        "./src/**/*.vue",
        "./resources/**/*.php",
        "./resources/**/*.html",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class",
    theme: {
        borderColor: (theme) => ({
            ...theme("colors"),
            DEFAULT: "#e2e8f0",
        }),
        extend: {
            colors: {
                theme: {
                    1: "#900c3e",
                    2: "#F1F5F8",
                    3: "#9c0631",
                    4: "#a70634",
                    5: "#dee7ef",
                    6: "#5e0728",
                    7: "#365A74",
                    8: "#D2DFEA",
                    9: "#91C714",
                    10: "#b80d4e",
                    11: "#F78B00",
                    12: "#FBC500",
                    13: "#7F9EB9",
                    14: "#E6F3FF",
                    15: "#8DA9BE",
                    16: "#607F96",
                    17: "#FFEFD9",
                    18: "#D8F8BC",
                    19: "#E6F3FF",
                    20: "#900c3e",
                    21: "#a70634",
                    22: "#a70634",
                    23: "#D6E1FF",
                    24: "#a70634",
                    25: "#C6D4FD",
                    26: "#E8EEFF",
                    27: "#98AFF5",
                    28: "#a70634",
                    29: "#900c3e",
                    30: "#8da3e6",
                    31: "#ffd8d8",
                    32: "#a70634",
                    33: "#4ab3f4",
                    34: "#517fa4",
                    35: "#a70634",
                    36: "#d18d96",
                    37: "#c7d2ff",
                    38: "#900c3e",
                    40: "#a70634",
                    41: "#BBC8FD",
                },
                dark: {
                    1: "#293145",
                    2: "#232a3b",
                    3: "#313a55",
                    4: "#1e2533",
                    5: "#3f4865",
                    6: "#2b3348",
                    7: "#181f29",
                },
                gray: {
                    100: "#f7fafc",
                    200: "#edf2f7",
                    300: "#e2e8f0",
                    400: "#cbd5e0",
                    500: "#a0aec0",
                    600: "#718096",
                    700: "#4a5568",
                    800: "#2d3748",
                    900: "#1a202c",
                },
            },
            fontFamily: {
                roboto: ["Roboto"],
            },
            container: {
                center: true,
            },
            maxWidth: {
                "1/4": "25%",
                "1/2": "50%",
                "3/4": "75%",
            },
            screens: {
                sm: "640px",
                md: "768px",
                lg: "1024px",
                xl: "1280px",
                xxl: "1600px",
            },
            strokeWidth: {
                0.5: 0.5,
                1.5: 1.5,
                2.5: 2.5,
            },
        },
    },
    variants: {
        extend: {
            zIndex: ["responsive", "hover"],
            position: ["responsive", "hover"],
            padding: ["responsive", "last"],
            margin: ["responsive", "last"],
            borderWidth: ["responsive", "last"],
            backgroundColor: [
                "last",
                "first",
                "odd",
                "responsive",
                "hover",
                "dark",
            ],
            borderColor: [
                "last",
                "first",
                "odd",
                "responsive",
                "hover",
                "dark",
            ],
            textColor: ["last", "first", "odd", "responsive", "hover", "dark"],
        },
    },
};
